[package]
name = "djsetjoiner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
dialoguer = "0.11.0"
glob = "0.3.1"
id3 = "1.10.0"
shlex = "1.2.0"
tempfile = "3.8.1"
